#pragma once

// 以下 define 定义了一系列与该类有关的错误
#define RESECTION_SUCCESS 1
#define RESECTION_INDEX_OUT_OF_RANGE -1
#define RESECTION_EXTERIOR_ELEMENTS_IS_NOT_INITED -2
#define RESECTION_GCP_NOT_ENOUGH -3
#define RESECTION_ROTATE_MATRIX_IS_NOT_3_3_MATRIX -4
#define RESECTION_MEASURE_SCALE_NOT_CALCULATED -5
#define RESECTION_SOME_GCP_IN_ONE_LINE -6
#define RESECTION_SOME_GCP_IN_ONE_CYLINDRICAL_SURFACE -7
#define RESECTION_CALC_A_OUT_MATRIX_IS_EMPTY -11
#define RESECTION_CALC_A_OUT_MATRIX_IS_NOT_A_2_6_MATRIX -12
#define RESECTION_CALC_A_ROTATE_MATRIX_IS_EMPTY -13
#define RESECTION_CALC_l_OUT_MATRIX_IS_EMPTY -21
#define RESECTION_CALC_l_OUT_MATRIX_IS_NOT_A_2_1_MATRIX -22
#define RESECTION_CALC_l_ROTATE_MATRIX_IS_EMPTY -23
#define RESECTION_CORRECT_EXTERIOR_CORRECTING_NUMBERS_NOT_ENOUGH -31

#include "ISpaceResection.h"

#include "DataTypes.h"